FROM ubuntu:20.04

# Copy over binaries from the build-env
COPY --from=desmoslabs/builder:latest /code/build/mage /usr/bin/mage

EXPOSE 26656 26657 1317 9090

# Run mage by default, omit entrypoint to ease using container with mage
CMD ["mage"]